### PR TITLE
Add premake

### LINKED ISSUE #7: Use a better AMX version
The AMX version used here is actually not the same one as SA-MP and therefore not compatible. This is clearly visible by comparing a certain AMX's function (that gets exported by the SA-MP plugin API) prototype.

Our amx_GetPublic: https://github.com/multitheftauto/amx/blob/4a8e51e43615f31f2038cb24823d6b9ef5799658/amx-deps/src/amx/amx.c#L1712

[SA-MP plugin SDK](https://github.com/maddinat0r/samp-plugin-sdk/blob/1d2e63238012d6ecac44326ca3a83e739cb783c6/amxplugin.cpp#L425)'s amx_GetPublic:
```c
int AMXAPI amx_GetPublic(AMX *amx, int index, char *funcname)
```

The pawn-lang team has a working AMX that's the most compatible with SA-MP and compiles on Linux (open source AMX used to be broken on linux some time ago) on a [specific branch of the compiler repository](https://github.com/pawn-lang/compiler/tree/Branch_burger) (which actually contains the whole source code of everything regarding AMX/Pawn). We should use it as well.

### PR DESCRIPTION
**Pull request by qaisjp**
This PR has only been tested on Windows!
Also switches to a better AMX version, so this fixes #7.

Additional tasks:

- [x] Fix mixed indentation (ffs)
- [x] Target should be `king`
- [ ] Get Linux working (does king even work on Linux at all?)
- [x] If possible, move amx to its own project?
- [ ] Add instructions
    - [ ] Get premake5.exe from premake-core github releases
    - [ ] How to generate the solution `./premake5.exe vs2019`
    - [ ] Recommend creating a symlink in your modules folder

### CODE REVIEW

**Comment by theSpool** [comment]
Would it be OK for me to push the latest AMX to this branch? Then I can get rid of the AMX version problems and get Linux running as well, all under premake.

**Comment by theSpool** [comment]
By the way, how does one get lua5.1.so?
https://github.com/multitheftauto/amx/blob/e374a2b26e9da785cd7ee18bd5bb10dd6643e6b2/amx-deps/src/premake5.lua#L72

**Comment by qaisjp** [comment]
Feel free to push to this branch.

lua5.1.so: don't know I just copied the config from https://github.com/multitheftauto/mtasa-blue/pull/120

**Comment by theSpool** [comment]
I went ahead and built lua5.1.so by myself to have it in the lib folder for everyone else to build (since the Windows .lib files where already there anyways). I'll merge master to this PR otherwise it won't build. Linux should build now, I haven't tested it yet though.

**Pull request merged**
